/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideBar: typeof import('./src/components/general/AsideBar.vue')['default']
    AsignUsers: typeof import('./src/components/sysControl/AsignUsers.vue')['default']
    AssignUsers: typeof import('./src/components/sysControl/PerAssignUsers.vue')['default']
    BottomSign: typeof import('./src/components/general/BottomSign.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    LogFilter: typeof import('./src/components/sysControl/LogFilter.vue')['default']
    LogRecords: typeof import('./src/components/sysControl/LogRecords.vue')['default']
    PerAssignUsers: typeof import('./src/components/sysControl/PerAssignUsers.vue')['default']
    PerRoles: typeof import('./src/components/sysControl/PerRoles.vue')['default']
    PerRoleUsers: typeof import('./src/components/sysControl/PerRoleUsers.vue')['default']
    Roles: typeof import('./src/components/sysControl/PerRoles.vue')['default']
    RoleUsers: typeof import('./src/components/sysControl/PerRoleUsers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubAddNewCom: typeof import('./src/components/sysControl/SubAddNewCom.vue')['default']
    SubAddNewGroup: typeof import('./src/components/sysControl/SubAddNewGroup.vue')['default']
    SubAddNewGroupConfirm: typeof import('./src/components/sysControl/SubAddNewGroupConfirm.vue')['default']
    SubList: typeof import('./src/components/sysControl/SubList.vue')['default']
    TopBar: typeof import('./src/components/general/TopBar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
