/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideBar: typeof import('./src/components/general/AsideBar.vue')['default']
    BottomSign: typeof import('./src/components/general/BottomSign.vue')['default']
    CalAddEvent: typeof import('./src/components/sysControl/CalAddEvent.vue')['default']
    CalDelEvent: typeof import('./src/components/sysControl/CalDelEvent.vue')['default']
    CalEventDesc: typeof import('./src/components/sysControl/CalEventDesc.vue')['default']
    CalEvents: typeof import('./src/components/sysControl/CalEvents.vue')['default']
    CalUpEvent: typeof import('./src/components/sysControl/CalUpEvent.vue')['default']
    CusAddSug: typeof import('./src/components/sysControl/CusAddSug.vue')['default']
    CusDelSug: typeof import('./src/components/sysControl/CusDelSug.vue')['default']
    CusSugDetail: typeof import('./src/components/sysControl/CusSugDetail.vue')['default']
    CusSugList: typeof import('./src/components/sysControl/CusSugList.vue')['default']
    CusUpSug: typeof import('./src/components/sysControl/CusUpSug.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    LogFilter: typeof import('./src/components/sysControl/LogFilter.vue')['default']
    LogRecords: typeof import('./src/components/sysControl/LogRecords.vue')['default']
    NotiAddNotice: typeof import('./src/components/sysControl/NotiAddNotice.vue')['default']
    NotiDelNotice: typeof import('./src/components/sysControl/NotiDelNotice.vue')['default']
    NotiList: typeof import('./src/components/sysControl/NotiList.vue')['default']
    NotiUpNotice: typeof import('./src/components/sysControl/NotiUpNotice.vue')['default']
    PerAssignUsers: typeof import('./src/components/sysControl/PerAssignUsers.vue')['default']
    PerRoles: typeof import('./src/components/sysControl/PerRoles.vue')['default']
    PerRoleUsers: typeof import('./src/components/sysControl/PerRoleUsers.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubAddNewCom: typeof import('./src/components/sysControl/SubAddNewCom.vue')['default']
    SubAddNewGroup: typeof import('./src/components/sysControl/SubAddNewGroup.vue')['default']
    SubAddNewGroupConfirm: typeof import('./src/components/sysControl/SubAddNewGroupConfirm.vue')['default']
    SubChangeGroupAdminPwdConfirm: typeof import('./src/components/sysControl/SubChangeGroupAdminPwdConfirm.vue')['default']
    SubList: typeof import('./src/components/sysControl/SubList.vue')['default']
    SysNotices: typeof import('./src/components/dashboard/SysNotices.vue')['default']
    TopBar: typeof import('./src/components/general/TopBar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
