export const USER_INFO = 'userInfo'
export const DEVICE_INFO = 'deviceInfo'
export const INIT_WEBSITE = 'initWebsite'
export const PERSONAL_SETTING = 'personalSetting'
export const SYS_PER_ROLE = 'sysPerRole'
export const OMS_SERVER_LOGS = 'OmsServerLogs'
